name: Infrastructure
on:
    workflow_dispatch:

jobs:
    Deploy_Infrastructure:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '14'

            - name: AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                aws-access-key-id: '${{ secrets.TF_USER_AWS_KEY }}'
                aws-secret-access-key: '${{ secrets.TF_USER_AWS_SECRET }}'

            - name: Terraform Init
              run: terraform init

            - name: Terraform Validate
              run: terraform validate
            
            - name: Terraform plan
              run: terraform plan

            - name: Terraform Apply
              run: terraform apply -auto-approve
